### ISSUE TITLE
[CODE REVIEW]  <Abanoub-Asaad>

### ISSUE THREAD

**Issue by abanoub-asaad** [imabp/code-review#10]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [ ] JavaScript
- [ ] Python
- [x] Others if yes, mention here : Java 

GitHub Link: https://github.com/Abanoub-Asaad/Game-Box

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by abanoub-asaad** [comment]
Firstly, Thank you in advance for your initiative 
Secondly, What do you think about this repository?

**Comment by imabp** [comment]
We are reviewing your project.. 
Few more hours.

**Comment by imabp** [comment]
Hey @Abanoub-Asaad 
I completely get the project 
It's good, that you have shared screenshots.

But I feel if you can extract something from the `docs/pdf` to your Main Readme. 
like architecture, how it is working and all-important points.. will make it more clear and will show your technical proficiency right up in front. You can refer to this, [here](https://github.com/imabp/webterminal), how a project readme should look like.

Lot of code can be refactored into modules. This helps to make sure, which part of your code is doing which function.
Refactoring Code Functions, into controllers, handlers, loaders, etc. can help you a lot.

Loved how you used docstrings :)

**Comment by imabp** [comment]
Feel free to ask :)

**Comment by abanoub-asaad** [comment]
Thank you so much for your feedback
I appreciate your efforts and time.

I have some questions : 
1. Should I run the project in the interview or What's happening in the interview process?
2. How should I prepare myself for the interview?

**Comment by imabp** [comment]
You need to walkthrough your code. No presentations nothing, just talk and walkthrough..

**Comment by abanoub-asaad** [comment]
Great! thank you Abir.
