### ISSUE TITLE
[CODE REVIEW]  <kahanikaar>

### ISSUE THREAD

**Issue by sanjibansg** [imabp/code-review#11]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [x] JavaScript
- [x] Python
- [ ] Others if yes, mention here : 

GitHub Link: 
https://github.com/deluminators/Matix

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
I went through the project. Really good work. @kahanikaar 
But these stuff concerns me a lot. 
- In Documentation (i.e. Readme) . - split things into important points only.
- In Contribution, please mention, the GitHub usernames.
- If you have worked in Team, Make a Project Board that shows, how you are tracking your progress.
-  Extract the Architectural flow from `pitch deck and use it in Project Readme.
- Need better  Code Collaboration Practice as it is a team project. Lot of files, in single commit. This will take the project out in first review. Make sure you collaborate and build project, with meaningful commits.  

- Avoid uploading `lock` files such as `package-lock.json` or `yarn. lock`
https://github.com/deluminators/Matix/blob/main/Application%20Code/Myproject/frontend/package-lock.json
-  Huge chunks of code are commented. Please remove them from the production code.
https://github.com/deluminators/Matix/blob/main/Application%20Code/Myproject/frontend/src/optimization/forecastData.js#L120-L240
https://github.com/deluminators/Matix/blob/d5a0ca4cdcf7ace7dd31d12bcb094f382cf1d0f8/Application%20Code/Myproject/frontend/src/optimization/bufferLinesCalculator.js#L44-L58
https://github.com/deluminators/Matix/blob/d5a0ca4cdcf7ace7dd31d12bcb094f382cf1d0f8/Application%20Code/Myproject/frontend/src/optimization/optimize.js#L129-L142

I hope you will work on them. Let me know, if you have any more stuff to discuss.
I am closing the issue, for reducing the overhead. But we are listening to you, feel free to comment down.

**Comment by sanjibansg** [comment]
Thanks a lot for that review! @imabp 
I did certain changes as per your recommendation, will follow your suggestions on further team projects.
Thanks again.
