### ISSUE TITLE
[CODE REVIEW]  <kothariji>

### ISSUE THREAD

**Issue by kothariji** [imabp/code-review#13]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [x] JavaScript
- [ ] Python
- [ ] Others if yes, mention here : 

GitHub Link: https://github.com/kothariji/SyntaxMeets

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
@kothariji
Feeling great about this project and has a good impact index. Will be using it personally, to brush up on some amazing algos.

- Just remove the huge chunk of commented code.
https://github.com/kothariji/SyntaxMeets/blob/master/backend/server/Utils/Rooms.js#L1-L18

- Remove the default generated readme, if you are explaining the installation on project readme.
https://github.com/kothariji/SyntaxMeets/blob/master/frontend/syntaxmeets/README.md

- Write test cases, for your language convertions, I dont see the code change, while, switching languages. May be I broke your project. But make sure, you write test cases, as this project fits for it.

- Just write a clean and highly maintainable code practice here at these lines. ( See below point )
https://github.com/kothariji/SyntaxMeets/blob/3dc6af5e7a85e98edda080e451320423d936e905/frontend/syntaxmeets/src/util/util.js#L19-L65

- My personal note for the above point will be you can do it like this as shown below. This makes sure, whenever you are adding more languages, you are just pushing things, into an array, in the format of `['languageName, 'extension']`. This also helps you to create maintainable code on a large scale, or designing any decorator function, reduces the overhead, and introduces clean code. 

```js
export const getExtensionByLangCode = (langCode) => {

    let fileExtensions = [ ["C++","cpp"], ["JAVA","java"], ["JavaScript","js"] ]

    for ( let i = 0; i<fileExtensions.length; i++)
    switch(langCode)
    {
        case fileExtensions[i][0]: return fileExtensions[i][1];
    }
}


```

Remove Unused files:
https://github.com/kothariji/SyntaxMeets/blob/master/frontend/syntaxmeets/src/App.test.js
https://github.com/kothariji/SyntaxMeets/blob/master/frontend/syntaxmeets/src/index.css

**Comment by imabp** [comment]
Do let us know if you have any further queries.

**Comment by kothariji** [comment]
@imabp Thank you so much. 🚀 
I really appreciate that you took out the time to review my project.
I understood all the points that you mentioned. I will try to work on the same.

Thank you once again @imabp 🙏 ❤️

**Comment by imabp** [comment]
All my pleasure @kothariji 
All the best for the applications :)
I am finding your project a really good one. Used last night with my `developer+problem solving` friends :P
