### ISSUE TITLE
[CODE REVIEW]  <shivakanthsujit>

### ISSUE THREAD

**Issue by shivakanthsujit** [imabp/code-review#14]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [ ] JavaScript
- [x] Python
- [ ] Others if yes, mention here : 

GitHub Link: https://github.com/shivakanthsujit/RL-for-Controller-Tuning

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by HarshCasper** [comment]
Hi @shivakanthsujit 

Great Project :tada: 

Here are a couple of pointers that cross my mind while reviewing it: 

- It appears as if you have packaged the application. It would be great if you can publish it over `pip` for better access. 
- Separate the Installation Instructions from the Usage. Break down your documentation into something that can be easily navigated and crisply followed. 
- Keep all your Notebooks and experiments in a separate directory for a consistent directory structure.
- Keep all your Source Code Files in a separate directory for a consistent directory structure. 
- Dockerize the application for easy installation and running up. (Expect interview questions on your Dockerfile)
- Add a Release to your Repository for a more consistent development workflow.
- Use Docstrings to document your Code (+1 if you can setup a Sphinx Docs Site for continuously building and publishing Docs) at all the places

Let me know if you have any further questions.

**Comment by shivakanthsujit** [comment]
Thanks for the review! I have been meaning to publish the package. I shall do that 👍 The other suggestions are really helpful too!
