### ISSUE TITLE
[CODE REVIEW]  <Vishruta-Patil>

### ISSUE THREAD

**Issue by Vishruta-Patil** [imabp/code-review#15]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [x] JavaScript
- [ ] Python
- [ ] Others if yes, mention here : 

GitHub Link: 
https://github.com/Vishruta-Patil/VChat-App---Realtime-Chat-Application

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
Hello, @Vishruta-Patil Overall the project is decent and good.
Here are some points you should work on.

- Project Readme, should discuss insights, architecture, and contribution guidelines. It helps other open source contributors, to understand the need of the project. You can use this template for readme. [here](https://github.com/imabp/webterminal)

- Please host your project, as this helps the reviewer, to see your project in action. You may use, Netlify for the frontend and Heroku for the backend.

- If possible, try to make your code modular, by implementing decorator functions in this file.
https://github.com/Vishruta-Patil/VChat-App---Realtime-Chat-Application/blob/master/utils/users.js

That's all for now, I hope to see more features :)

**Comment by imabp** [comment]
Feel free to ask, any query.

**Comment by Vishruta-Patil** [comment]
Thanks a lot @imabp
