### ISSUE TITLE
[CODE REVIEW]  <Your GitHub Username>

### ISSUE THREAD

**Issue by abhishekrawe** [imabp/code-review#19]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [ ] reactjs
- [ ] nodejs 
- [ ]  socket-io 

GitHub Link:   https://github.com/abhishekrawe/Collaborative_white_board

Thank you for this super-impacting initiative.

**Comment by imabp** [comment]
Hello @abhishekrawe 
Thanks for your patience.
-> First thing, make regular commits and have proper commit messages.  
-> As I see there are only 5 commits, this puts a bad impression as a reviewer, that the applicant has not invested time in learning and committing to the work.
-> Deploy it to Netlify or Azure.
-> The project readme looks good. But seeing commit history, it doubts me as a reviewer, whether the project is authentic or not.

You need to work on these @abhishekrawe , as these are the important stuff during admission process to get accepted in fellowship. Please see the video [here](https://www.youtube.com/watch?v=cEDCV2HJxcU) before you start improvising
