### ISSUE TITLE
[CODE REVIEW]  <abhi-824>

### ISSUE THREAD

**Issue by abhi-824** [imabp/code-review#4]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [ ] JavaScript
- [ ] HTML/CSS
- [ ] NodeJs, Web Sockets

GitHub Link: https://github.com/abhi-824/Game-of-CODES

Thank you for this super-impacting initiative.

**Comment by imabp** [comment]
- These unnecessary files should be removed
https://github.com/abhi-824/Game-of-CODES/blob/master/routes/screens.js

- The Readme is looking great with all the **usage information**
But it really misses the information as a contributing guide. Do discuss the project architecture on Readme.

- You can perform code refactorization in `server.js`. I see it is possible to refactor lot of code.

- Huge chunk of code is commented. You should remove them
https://github.com/abhi-824/Game-of-CODES/blob/master/server.js#L464-#L482

- This directory needs a lot of code cleaning.
https://github.com/abhi-824/Game-of-CODES/tree/master/publicis

**Comment by imabp** [comment]
Let us know if you have any more queries. :)

**Comment by abhi-824** [comment]
Thanks a lot for your reply. I had this doubt: should I convert it into Reactjs? Like I completed this project when I had absolutely no knowledge of reactjs and somehow it became my one of the best projects. But as it is quite big, it maybe a huge task for me to convert it into react. So, converting to Reactjs would help project look more professional? And using plain HTML/CSS is a problem in my interviews?
