### ISSUE TITLE
[CODE REVIEW]  Naman-1234

### ISSUE THREAD

**Issue by Naman-1234** [imabp/code-review#7]
Hello, Sorry I  know that this might be not the platform to ask such a thing, But can anyone tell me what is the last date for applying for mlh fellowship. I didn't find anything related to this on their website.

Tech Stack: 
- [ ] JavaScript
- [ ] Python
- [ ] Others if yes, mention here : 

GitHub Link: 

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by HarshCasper** [comment]
> Hello, Sorry I know that this might be not the platform to ask such a thing, But can anyone tell me what is the last date for applying for mlh fellowship. I didn't find anything related to this on their website.
> 
> Tech Stack:
> 
> * [ ]  JavaScript
> * [ ]  Python
> * [ ]  Others if yes, mention here :
> 
> GitHub Link:
> 
> Thank you for this super-impacting initiative.
> 
> * [ ]  I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

Applications are open throughout the year. You will be able the applications open right here with the corresponding batches: 

- [Open Source](https://fellowship.mlh.io/programs/open-source)
- [Software Engineering](https://fellowship.mlh.io/programs/software-engineering)
- [Prodiction Engineering](https://fellowship.mlh.io/programs/production-engineering)

It is highly advisable not to delay till the last minute for sending in your applications. If you do that, many of the prospective fellows would have been interviewed and accepted into the Fellowship. It's done on a "First Come, First Serve" basis. 

Let us know if you have any more questions.

**Comment by imabp** [comment]
Thank you @HarshCasper 
@Naman-1234 I hope it clears your concern. 
Thank you for asking. Closing the issue.
