### ISSUE TITLE
[CODE REVIEW]  <pranjalbareth>

### ISSUE THREAD

**Issue by pranjalbareth** [imabp/code-review#8]
Hello, please help me with the code review for the following code sample.

I have a little confusion on which project I should submit in the form. Please suggest which project would be better for submission, out of the two mentioned below.

###  Project  1 - Mini Social Media
Tech Stack: 
- [x] JavaScript
- [x] Firebase
- [ ] Others if yes, mention here : None

GitHub Link: 
https://github.com/pranjalbareth/flux-india

###  Project  2 - A Blogging Platform

Tech Stack: 
- [x] Django
- [x] Bootstrap
- [ ] Others if yes, mention here : None

GitHub Link: 
https://github.com/pranjalbareth/devlogs

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
Hello @pranjalbareth 

The code sample to be chosen should reflect your technical proficiency. 
I have talked about it here: https://youtu.be/ZafLMjcMnUw
I feel both project, shows your technical proficiency in Python and Javascript, so choose based on that.
_On a personal note, I found you write more clean code in JavaScript_

- Project Readme is not complete. It should have decent `about the project` insights, how it is built, the `architecture`, the `usage guidelines`, and `contributing guidelines` for open source contributors. 

- I loved one thing about the files in the project, that you have used the docstrings in every file. 

- Huge chunk of code is commented. Please remove them
https://github.com/pranjalbareth/flux-india/blob/8fbd6a4a7a324e3c3ffcfe90e675500ac8bd77b7/src/containers/create-post/index.js#L115-L164

- Please update manifest.json. This helps you when you share your project link on mobile or WhatsApp
https://github.com/pranjalbareth/flux-india/blob/main/public/manifest.json

@harshcasper may have more additions to this ;:)

Goodluck :)

**Comment by imabp** [comment]
Closing the issue, for now to clear overhead. 
But we are listening to you. Feel free to put up the conversation

**Comment by pranjalbareth** [comment]
Thanks a lot, Abir ✨

I'll make the suggested corrections. 🚀
Now, just waiting for @/HarshCasper 's review now.

**Comment by Naman-1234** [comment]
@imabp  One thing I need to ask sir,Which is better providing multiple projects <strong>or</strong> a single one <strong>or</strong> providing some code snippets from different projects showing proficiency in individual?

**Comment by imabp** [comment]
A single project, which shows your technical proficiency

**Comment by Naman-1234** [comment]
@imabp Thanks sir I just have few more questions ,If you could help in answering them that would be great:
- Could we continue working on the project we provided the link to them or does it leave a bad impression. I am currently working on a project(WIll be built by today or tomorrow) but the styling part will remain.
- I have done some contributions in open source, How could I use them to my use here?
Looking forward for a reply.Thanks.

**Comment by imabp** [comment]
Obviously, when you started building a project, you may have a goal in your mind.. Completely makes sense.. Just make it a project GitHub release, if you have released up your project. 
Code sample should show, your technical proficiency. I repeat. 
Whatever you submit, it should represent your technical proficiency.
