### ISSUE TITLE
[CODE REVIEW]  <gupta-piyush19>

### ISSUE THREAD

**Issue by gupta-piyush19** [imabp/code-review#9]
Hello, please help me with the code review for the following code sample.

Tech Stack: 
- [x] JavaScript
- [x] MERN
- [x] Draft,js
- [ ] Others if yes, mention here : 

GitHub Link: https://github.com/gupta-piyush19/Blogic

Thank you for this super-impacting initiative.
- [ ] I wish to donate [here](https://www.buymeacoffee.com/imabp) for your efforts, time, and support.

**Comment by imabp** [comment]
Please have proper documentation(Project Readme) discussing about the project abstract, usage guidelines, architecture and contributing guidelines.

Do not upload **lock files**, like `yarn.lock` and `package-lock.json`
Add them to gitignore.

The rest of the code looks good to me. It's clean
Loved how the docstring is used

**Comment by gupta-piyush19** [comment]
Thankyou sir for your valuable feedback, I'll definitely improve it.
